### ISSUE TITLE
EsmtpKeyword warning AUTH=PLAIN

### ISSUE THREAD

**Issue by rubo77** [dac-gmbh/new-tokio-smtp#5] opened 2020-05-30 23:36 UTC
I get this error:

https://github.com/dac-gmbh/new-tokio-smtp/blob/d6b19893be525a1d3f81974ec0081ca96db9b499/src/data_types.rs#L324

in my rust app (see https://github.com/freifunk-saar/ff-node-monitor/issues/63#issuecomment-636367280)

How is this error raised? please can you add more hints, what is wrong with the string in the error message?

**Comment by rustonaut** [comment] 2020-05-31 12:18
I noticed there is a bug and a syntax error in a `EsmtpValue` can also trigger and an `EsmtpKeyword` syntax error instead of `EsmtpValue` syntax error.

esmtp keywords must have at least one character and all characters must be ascii and alpha numeric or `-`. Through the first character is not allowed to be `-`.

esmtp values must be asci, no ctrl characters, no whitespace  and not `=` character (through there can be whitespace around a esmtp value as far as I can remember). 

This roughly maps to the Esmtp keyword and value syntax constructs in the rfc's (I have to lookup which).

**Comment by rustonaut** [comment] 2020-05-31 12:32
So it's [RFC 5321](https://tools.ietf.org/html/rfc5321).

So `EsmtpKeyword` maps to basically smtp extension names and extension parameter names, and `EsmtpValue` to extension parameter values.

For example the `SMTPUTF8` which needs to be added to some commands to send handle internationalized mails addresses is a `EsmtpKeyword` and so is the capability reported with ehlo.

**Comment by rustonaut** [comment] 2020-05-31 12:54
So the problem is either because it's wrongly used (unlikely I guess) or
because the helo/ehlo response does have some syntax error or something
the library can not parse.  

*Do you happen to have the ehlo respone?*

In the linked issue you have the HELO response, but `helo` was replaced
by `ehlo` which besides other thinks reports back which capabilities the server
does support, which is probably where the error comes from.

**Comment by rustonaut** [comment] 2020-05-31 12:58
I opened following issues wrt. to that:

- https://github.com/dac-gmbh/new-tokio-smtp/issues/7
- https://github.com/dac-gmbh/new-tokio-smtp/issues/6

Even if the EHLO response server syntax is wrong (or the parsing code of this library) it should just 
ignore not parsable lines and go on. 

Through I guess it also should log an warning, containing the not parsable line.

**Comment by RalfJung** [comment] 2020-05-31 13:32
@rustonaut can you explain how to get the EHLO response via telnet? Then @rubo77 might be able to provide it.

**Comment by RalfJung** [comment] 2020-05-31 13:33
Also, beyond being more accepting of bad syntax, it would also help if the `EsmtpKeyword` error variant would carry along the bad keyword: `EsmtpKeyword(String)` or so.

**Comment by rustonaut** [comment] 2020-05-31 14:03
Instead of sending/typing `HELO ****.de` you type send `EHLO  ****.de`. 

The difference is then in the response which lists all capabilities/esmtp extensions the server does support.

**Comment by rustonaut** [comment] 2020-05-31 14:27
Also for redacted information `***` please tell me if any of them is non us-ascii.

**Comment by rustonaut** [comment] 2020-05-31 15:35
I published a new version which is more lenient with ehlo responses it cannot parse. (v0.8.2)

I also added more information onto the errors (0.9 branch on github) but this is a API braking change so this will go into v0.9. And likely changes some interfaces to return warning errors with the `Result::Ok` variant instead of logging the warnings (with some utility method which strips the warnings and logs them, and another which errors if there are warning  errors). But not tody and I have to thing about this a bit more.

**Comment by rubo77** [comment] 2020-06-01 23:31
> Also for redacted information `***` please tell me if any of them is non us-ascii.

The reacted information ***** only contained ascii letters

I also added the EHLO output of telnet here: https://github.com/freifunk-saar/ff-node-monitor/issues/63#issuecomment-637179209

**Comment by rustonaut** [comment] 2020-06-02 10:52
Ok, thanks.

I already published a patch update to the library, which is skipping over "un-parsable" ehlo responses,
through it will also log the error (to the `log` facade). I have some better ways to do it. But they brake the API and the tail of this issue might brake the API anyway in other ways, too. So it's just skip+warn.

With that some warning like the following is logged:

`Parsing Server EHLO response partially failed: syntax error parsing esmtp-keyword from str`

But otherwise it should work.

Data what failed isn't carried on in the v0.8.2 patch due to API braking when doing so, but I'm testing on the coming v0.9 so I see more error info ;=)

---------------

Now to find out what exactly the bug is I have to dive into the RFC, it seems that Postfix is responding twice (first with a 220 response which is the same as EHLO, and then another 250 multi-line response which _again_ contains the *****.de domain. So then the code tries to parse that as a EHLO Keyword, but it fails as it contains a '.' which isn't allowed in that position...

But I'm not sure how far this is standard conform and how it exactly works out.

**Comment by rustonaut** [comment] 2020-06-02 11:21
> EHLO ****.de
> 220 ****.de ESMTP Postfix (Debian/GNU)      // First response
> 250-****.de                                                      //  Second response, duh?

But I think I have an idea what went wrong. My guess it's not responding twice but the initial greeting somehow sneaked in there or is wrongly parsed. This would also explain why there is no flow control related error

**Comment by RalfJung** [comment] 2020-06-03 11:46
> I published a new version which is more lenient with ehlo responses it cannot parse. (v0.8.2)

Looks like this fixed @rubo77's problem :D (https://github.com/freifunk-saar/ff-node-monitor/issues/63#issuecomment-638133829)

**Comment by rubo77** [comment] 2020-06-03 11:53
https://github.com/dac-gmbh/new-tokio-smtp/commit/69e1fecdb754c5c1b114c2913ff400d78a61cb9b

**Comment by rustonaut** [comment] 2020-06-03 19:59
The only think is that I'm still stumped what actually went wrong.

When I manually feed it with the telenet log it just works without
any parse error.

I also checked the flow control code, buffer IO code and StartTls to
see if there is any chance of "partially" parsed buffers bleeding in
the next command or similar. But as far as I can tell this can't happen.

I also checked the RFC if I overlooked something wrt. to the EHLO command,
the initial greeting or the continuation after StartTls but wasn't able to find anything.

You see the EsmtpKeyword parsing functionality is only used by EHLO response parsing
and no other command. And before it's used the servers id (~=domain*) is announced and
parsed, which didn't fail. So somehow when using the functionality through the app an EHLO
response is somewhat different in that it's valid in it's first line but in a follow up line has some invalid keyword (or value, as there where that bug that value syntax errors where reported as keyword syntax errors)... 

Well anyway it works now and gave me an interesting idea for some kind of "inspection" feature which could make debugging this problems simpler if enabled. Not sure if this would have been possible in this case but it still would be helpful.

**Comment by RalfJung** [comment] 2020-06-14 14:28
@rubo77 in the latest ff-node-monitor, I added initialization of the log facade. I think `warn` are printed by default, so in principle your log should then tell us what the "bad EHLO response" is that has been causing all this trouble.

**Comment by rubo77** [comment] 2020-06-15 05:39
If this should show more error details here too? https://github.com/freifunk-saar/ff-node-monitor/issues/68 – it deosnt ;(

**Comment by rubo77** [comment] 2020-06-15 06:42
And on my online server there is no error output with the new update at all now when it is sending the email. 

How can I enforce the error again? so you can debug this further?

**Comment by RalfJung** [comment] 2020-06-15 15:41
Elsewhere @rubo77 reported that the warning they got is

> `Warning: Parsing Server EHLO response partially failed: syntax error parsing esmtp-keyword from str`

That doesn't say what is the wrong keyword though, is that expected @rustonaut ?

**Comment by rustonaut** [comment] 2020-06-15 18:34
Sadly yes, else it would have been an API breaking change or problematic
logging.

I have published a braking change update for new-tokio-smtp where this and
a number of other small improvements are included. I also published a new
version of mail where the only change is the dump in the version of the
SMTP library.

The new version also has support for trace level debugging. Through there
are some drawbacks. I will respond with a bit more details when I'm back on
my laptop so likely tomorrow (currently I'm writing from a phone).

**Comment by RalfJung** [comment] 2020-06-15 18:45
Unfortunately I cannot directly update the package, the dependency goes through a few indirections:
```
new-tokio-smtp v0.8.2
└── mail-smtp v0.2.2
    └── mail v0.6.12
        └── ff-node-monitor v0.1.0 (/home/r/src/freifunk/ff-node-monitor)
```

**Comment by rustonaut** [comment] 2020-06-15 18:57
Bumping mail to 0.7 should work the only change that version has is that it
uses mail-smtp 0.3 which only differs in using new-tokio-smtp 0.8.

While there was a API braking change it's unlikely that any library
depending on it is actually affected by the change. And if it's most likely
trivial to fix (for the author).

**Comment by rustonaut** [comment] 2020-06-15 19:00
I learned from it that reexporting types from a dependency while thinks are
still in flux can be more trouble then it seems ;=)

**Comment by RalfJung** [comment] 2020-06-15 19:06
Ah nice, I bumped the dependencies now. :)

@rubo77 you could try again to get a better error.

**Comment by rubo77** [comment] 2020-06-15 21:06
Now it sais: `Warning: Parsing Server EHLO response partially failed: syntax error parsing esmtp-keyword in "AUTH=PLAIN"`

(The email is successfully sent)

**Comment by rustonaut** [comment] 2020-06-15 21:22
That is indeed not valid SMTP. SMTP doesn't allow an equal sign between the
ehlo keyword and the parameters.

The syntax is:

`ehlo-line = ehlo-keyword *( SP ehlo-param)`

I.e. parameters must start with with a space.

The correct line would be:

`AUTH PLAIN`

**Comment by rustonaut** [comment] 2020-06-15 21:24
Do you know which software runs on the mail server so that an issue can be
opened there and I can find out why they use a `=` instead of a space as
separator?

**Comment by rustonaut** [comment] 2020-06-15 21:26
Also depending on circumstances I might add support for the malformed
syntax.

**Comment by rubo77** [comment] 2020-06-15 21:54
I use courier and postfix on my mail server:

```

ii  courier-authdaemon                     0.66.4-9                             amd64        Courier authentication daemon
ii  courier-authlib                        0.66.4-9                             amd64        Courier authentication library
ii  courier-authlib-mysql                  0.66.4-9                             amd64        MySQL support for the Courier authentication library
ii  courier-authlib-userdb                 0.66.4-9                             amd64        userdb support for the Courier authentication library
ii  courier-base                           0.76.3-5+deb9u1                      amd64        Courier mail server - base system
ii  courier-imap                           4.17.2+0.76.3-5+deb9u1               amd64        Courier mail server - IMAP server
ii  courier-imap-ssl                       4.17.2+0.76.3-5+deb9u1               all          Courier mail server - IMAP over TLS [transitional]
ii  courier-maildrop                       2.8.4+0.76.3-5+deb9u1                all          Courier mail server - mail delivery agent [transitional package]
ii  courier-pop                            0.76.3-5+deb9u1                      amd64        Courier mail server - POP3 server
ii  courier-pop-ssl                        0.76.3-5+deb9u1                      all          Courier mail server - POP3 over TLS [transitional]
ii  courier-ssl                            0.76.3-5+deb9u1                      all          Courier mail server - TLS Support [transitional]
ii  libcourier-unicode1:amd64              1.4-3+b1                             amd64        Courier Unicode library (shared runtime library)

**Comment by rubo77** [comment] 2020-06-15 22:32
I found this:

>RFC 2554 uses multiple values for the keyword AUTH as ESMTP command, which is allow by RFC 1869, 
however broke the parsing of several ESMTP client implementations. One work around is, to add artificially a "=" 
(equal sign) between the AUTH keyword and the value, eg. AUTH=LOGIN.

**Comment by rustonaut** [comment] 2020-06-15 22:36
I think I found out what is going on.

Postfix emits both (E.G.) `AUTH PLAIN LOGIN ` and  `AUTH=PLAIN LOGIN`

The later one seems to be done form of legacy compatibility thing as some
mail server and client somewhere in history send to have done that wrong
and was used enough to make postfix do that action.

As such just ignoring that malformed line is the right thing to do.

Through maybe it should not be warned against.

**Comment by rustonaut** [comment] 2020-06-15 22:42
Also I'm irritated why is a workaround as adding a = sing should have
broken parsing, too. Furthermore with at least some settings postfix does
use an = sign and still adds multiple valid (like in the snipped I posted
advice with auth plain and login).

Uhm, anyway luckily ignoring it is the right thing to do as a valid auth
line is still emitted.

**Comment by rustonaut** [comment] 2020-06-15 22:43
Sorry somehow messed up the previous post on smartphone. I'm back tomorrow
;=)

**Comment by rustonaut** [comment] 2020-06-17 20:51
I think the `AUTH=PLAIN` workaround works because the parsers in questions does use spaces for tokenizing and then "interprets" the keyword by just doing some kind of "starts with or similar check.

So they parse:

```
AUTH PLAIN LOGIN
AUTH=PLAIN LOGIN
````

As something like:

```
[ 
    ("AUTH", "PLAIN"),
    ("AUTH=PLAIN", "LOGIN")
]
```

Interpreting "AUTH=PLAIN" as just "AUTH" and as such parsing both `AUTH` `PLAIN` and `LOGIN` ;=)

Well mail is just quite messy.

Anyway luckily ignoring the "AUTH=PLAIN" lines is quite the right thing to do, but I guess it can make sense to not warn on "AUTH=PLAIN" errors, or at last document this in the README or similar.

So I'm closing this issue again. All which needs to be done for it is done.

**Closed by rustonaut** 2020-06-17 20:51 UTC
Labels: bug
